include:
    - "https://gitlab.com/manaplus/manaplus/raw/master/tools/ci/branches/.gitlab-ci_header.yml"
    - "https://gitlab.com/manaplus/manaplus/raw/master/tools/ci/branches/ci_gcc8_tests/.gitlab-ci.yml"
